Traceback (most recent call last):
  File "/home/khiner/ai_challenge/ants.py", line 289, in run
    bot.do_turn(ants)
  File "AStarBot.py", line 55, in do_turn
    self.ant_list[ant_loc].do_move_location(dest)
  File "/home/khiner/ai_challenge/Ant.py", line 32, in do_move_location
    self.path = self.aStar(self.ants.graph, self.loc, self.dest)
  File "/home/khiner/ai_challenge/Ant.py", line 57, in aStar
    for node in graph[source]:
KeyError: (28, 19)
turn    1 bot 0 timed out
